name: iOS Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Check files
        run: |
          pwd
          find . -maxdepth 5 -name "*.xcodeproj" -o -name "*.xcworkspace"

      - name: Build App
        run: |
          xcodebuild \
            -project "BayTech_Admin_SwiftUI_Files/Baytech Admin.xcodeproj" \
            -scheme "BayTech Admin" \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build