name: iOS Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build App
        run: |
          xcodebuild \
            -project "BayTech_Admin_SwiftUI_Files/Baytech Admin.xcodeproj" \
            -scheme "BayTech Admin" \
            -destination 'generic/platform=iOS Simulator' \
            build
